### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vimkill** [DVDishka/Backuper#18]
**Error occurred while enabling Backuper v2.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at ru.dvdishka.backuper.Backuper.onEnable(Backuper.java:44) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[bukkit-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[bukkit-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:490) ~[bukkit-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:527) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4090-Bukkit-38b1f49]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:453) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4090-Bukkit-38b1f49]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:615) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4090-Bukkit-38b1f49]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4090-Bukkit-38b1f49]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:241) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4090-Bukkit-38b1f49]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:979) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4090-Bukkit-38b1f49]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:296) ~[craftbukkit-1.20.4-R0.1-SNAPSHOT.jar:4090-Bukkit-38b1f49]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[bukkit-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[bukkit-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 12 more **

**win 10 64x, minecraft server core CraftBukkit version 4090-Bukkit-38b1f49 and minecraft version 1.20.4**

**I am starting the server, but for some reason the configuration file does not appear on the path plugins/Backuper/config.yml**

**Comment by DVDishka** [comment]
The backuper is working only with Paper or Paper fork cores. In case if you don't have to use exactly CraftBukkit I'm recommending you to switch your core to Paper because it has more functionality and better performance

**Comment by vimkill** [comment]
> The backuper is working only with Paper or Paper fork cores. In case if you don't have to use exactly CraftBukkit I'm recommending you to switch your core to Paper because it has more functionality and better performance

Thank you very much, this is my first server, and I wanted to put a backup on it, but I'm very bad at this.
