### ISSUE TITLE
Backuper2.0.jar not Working on Foila 1.20.4 [BUG]

### ISSUE THREAD

**Issue by Flodapo** [DVDishka/Backuper#19]
**Specify your operating system, minecraft server core and minecraft version**
Ubuntu, Foila 1.20.4

**Enter your config**
Just added Backuper to the Plugins Folder

**Describe the bug**
Error while starting Server and then the Plugin disabled itself

**Describe the way to reproduce the bug**
[01:01:28 ERROR]: Error occurred while enabling Backuper v2.0.0 (Is it up to date?)
java.lang.IllegalStateException: Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
	at ru.dvdishka.shade.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:169) ~[Backuper-2.0.0.jar:?]
	at ru.dvdishka.shade.commandapi.CommandAPI.onEnable(CommandAPI.java:135) ~[Backuper-2.0.0.jar:?]
	at ru.dvdishka.backuper.Backuper.onEnable(Backuper.java:20) ~[Backuper-2.0.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[01:01:28 INFO]: [Backuper] Disabling Backuper v2.0.0
[01:01:28 ERROR]: Error occurred while disabling Backuper v2.0.0
java.lang.UnsupportedOperationException: null
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.cancelTasks(CraftScheduler.java:348) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at ru.dvdishka.backuper.backend.common.Scheduler.cancelTasks(Scheduler.java:61) ~[Backuper-2.0.0.jar:?]
	at ru.dvdishka.backuper.Backuper.onDisable(Backuper.java:64) ~[Backuper-2.0.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by DVDishka** [comment]
Backuper uses some third-party plugin-libraries. In this case CommandAPI plugin crashed during server startup, so Backuper could not start either. Sorry, but I can't solve this problem for now as it's not really on my side. I will let you know when the bug is fixed. Thanks for your report

**Comment by Flodapo** [comment]
But why do you but Backuper on hangar with Foila 1.20.4 Support when it dosnt?
I can understand that it a bug on your Side but you cant say that it works when it dosnt.
Still Thanks for your Reply
https://hangar.papermc.io/Collagen/Backuper

**Comment by DVDishka** [comment]
Backuper supports older builds of Folia 1.20.4.

**Comment by DVDishka** [comment]
I just changed the description on hangar

**Comment by DVDishka** [comment]
You can try to get it from folia GitHub page

**Comment by DVDishka** [comment]
And build it yourself

**Comment by Flodapo** [comment]
I did and that seems to be the wrong version

**Comment by Flodapo** [comment]
as allways its a matter of time i guess. Still thanks for the help / clarification. Hope to use you plugin cus it annoying to do it manually and i often forget. Have a Nice Day

**Comment by DVDishka** [comment]
Thanks for your report

**Comment by DVDishka** [comment]
Now you can download Backuper-2.0.2-folia. It supports latest folia builds
