### ISSUE TITLE
Issues found and suggestions for improvement

### ISSUE THREAD

**Issue by TAN-Z-H** [DVDishka/Backuper#2]
Minecraft Version : git-Folia-"daacd42" (MC: 1.20.1)

config : I wiil send a file [config.txt](https://github.com/DVDishka/Backuper/files/12064428/config.txt)

Problems and Suggestion : 

1. When I limit the maximum number of backups, it doesn't take effect.
2. Compared to the backup plugin I use on Carpet, the backup speed still needs to be improved (I don't understand the difficulty and feasibility of improvement, please forgive my ignorance).
3. It is recommended to add the rollback function (automatically copy files after shutting down the server) in addition to the hot backup.

Thank you again for developing this plugin, it helped me a lot and thank you for your contribution to the development of Folia!

**Comment by DVDishka** [comment]
1. Thanks for reporting, i will check it
2. I will try to improve it
3. Thanks for the idea, i think it will be added in 1.5.0!

Thanks for using

**Comment by DVDishka** [comment]
Are the backups just not being deleted or is the wrong amount being deleted?

**Comment by DVDishka** [comment]
If you have fixedBackupTime option enabled, your backupPeriod becomes 24 hours automatically

**Comment by TAN-Z-H** [comment]
> 备份只是没有被删除还是删除了错误的数量？

The backup was not deleted gracefully.

**Comment by TAN-Z-H** [comment]
Look
[image](https://github.com/DVDishka/Backuper/assets/70757024/8344ef8c-8b37-49df-ac51-391f93187af9)

**Comment by TAN-Z-H** [comment]
But,You see,What I have set is 6.

**Comment by DVDishka** [comment]
Are you sure, that you are using 1.4.0?

**Comment by TAN-Z-H** [comment]
> Are you sure, that you are using 1.4.0?

yep

**Comment by TAN-Z-H** [comment]
![image](https://github.com/DVDishka/Backuper/assets/70757024/fe8dedc6-86fd-405f-be8a-cd8d06379b89)

**Comment by TAN-Z-H** [comment]
Maybe I can try reinstalling to see if it limits the number of backups normally .

**Comment by TAN-Z-H** [comment]
Now I reinstall and empty everything, including the yml file and zip file, change the limit to 5, manually back up 5 times, and observe that it still backs up the sixth time and does not delete the oldest files (the limit expires).

[latest.log](https://github.com/DVDishka/Backuper/files/12065073/latest.log)

**Comment by DVDishka** [comment]
Ok, thanks again for the report. I will fix it, but not until August 1, sorry

**Comment by TAN-Z-H** [comment]
> Ok, thanks again for the report. I will fix it, but not until August 1, sorry

It's okay, I can manually delete it for now. Thank you again for listening to my feedback.

**Comment by TAN-Z-H** [comment]
I'm really sorry, but now I've found the reason why backup is so different from my previous plugin's backup speed: I set uncompression in that plugin. Please forgive my stupidity. :/

**Comment by DVDishka** [comment]
No problem, i will try to improve it anyway

**Comment by DVDishka** [comment]
Try running the server as administrator and make a backup, maybe that will fix the bug

**Comment by DVDishka** [comment]
Try running the server as administrator and make a backup, maybe that will fix the bug

**Comment by abc110210** [comment]
[07:33:08 ERROR]: Error occurred (in the plugin loader) while disabling Backuper v1.4.1 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.cancelTasks(CraftScheduler.java:346) ~[folia-1.20.1.jar:git-Folia-17]
        at ru.dvdishka.backuper.common.classes.Scheduler.cancelTasks(Scheduler.java:60) ~[[备份]Backuper-1.4.1.jar:?]
        at ru.dvdishka.backuper.Backuper.onDisable(Backuper.java:92) ~[[备份]Backuper-1.4.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[folia-1.20.1.jar:
git-Folia-17]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.1.jar:git-Foli
a-17]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[folia-1.20.1.jar:g
it-Folia-17]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.1.jar:git-Folia
-17]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.1.jar:git-Folia-17]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:679) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:463) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[folia-1.20.1.jar:git-Folia-17]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.1.jar:git-Folia-17]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by DVDishka** [comment]
Thanks, ill check it
