### ISSUE TITLE
[BUG] Backuper v2.0.1 does not work in Paper 1.20.6 Build 65+

### ISSUE THREAD

**Issue by mmazur519** [DVDishka/Backuper#21]
[04:37:50 ERROR]: Error occurred while enabling Backuper v2.0.1 (Is it up to date?)
java.lang.NoSuchFieldError: Class net.minecraft.server.MinecraftServer does not have member field 'net.minecraft.commands.Commands vanillaCommandDispatcher'
	at Backuper-2.0.1.jar/ru.dvdishka.shade.commandapi.nms.NMS_Common.getBrigadierDispatcher(NMS_Common.java:353) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.shade.commandapi.CommandAPIBukkit.registerCommandNode(CommandAPIBukkit.java:641) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.shade.commandapi.CommandAPIHandler.register(CommandAPIHandler.java:664) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.shade.commandapi.AbstractCommandAPICommand.register(AbstractCommandAPICommand.java:307) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.shade.commandapi.CommandAPICommand.register(CommandAPICommand.java:60) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.shade.commandapi.Execution.register(Execution.java:38) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.shade.commandapi.AbstractCommandTree.register(AbstractCommandTree.java:66) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.shade.commandapi.CommandTree.register(CommandTree.java:32) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.shade.commandapi.ExecutableCommand.register(ExecutableCommand.java:236) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.backuper.backend.Initialization.initCommands(Initialization.java:190) ~[Backuper-2.0.1.jar:?]
	at Backuper-2.0.1.jar/ru.dvdishka.backuper.Backuper.onEnable(Backuper.java:40) ~[Backuper-2.0.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-68]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-68]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:609) ~[paper-1.20.6.jar:git-Paper-68]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:558) ~[paper-1.20.6.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[paper-1.20.6.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[paper-1.20.6.jar:git-Paper-68]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1142) ~[paper-1.20.6.jar:git-Paper-68]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-68]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[04:37:50 INFO]: [Backuper] Disabling Backuper v2.0.1
[04:37:50 INFO]: [Backuper] Backuper plugin has been disabled!

**Comment by DVDishka** [comment]
Specify your server core please

**Comment by mmazur519** [comment]
Ubuntu 22.04.4 LTS, paper-1.20.6 Build 68

**Comment by DVDishka** [comment]
Thanks for your report. One of the APIs was broken in 1.20.6 Build 65 and until it is not fixed the only thing I can recommend is to use Build 64

**Comment by DVDishka** [comment]
Did you try to run it on build 64?

**Comment by mmazur519** [comment]
I have not rolled back at this time but I do see the issue on the paper git between the version. At this time, I will just backup via startup script till issue in paper is patched.

**Comment by DVDishka** [comment]
Paper 1.20.6 support added in version 2.0.2
