### ISSUE TITLE
[BUG] Error while enabling Backuper on Folia 1.20.6

### ISSUE THREAD

**Issue by GrimPlayzs** [DVDishka/Backuper#23]
**Ubuntu Linux, Folia version 1.20.6-DEV-dev/1.20.6@78f49e0, 1.20.6*

**No config was generated**

**Plugin fails to enable**

**Install Backuper on a Folia 1.20.6 server**

Error occurred while enabling Backuper v2.0.2-folia (Is it up to date?)
java.lang.IllegalStateException: Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
	at Backuper-2.0.2-folia.jar/ru.dvdishka.shade.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:172) ~[Backuper-2.0.2-folia.jar:?]
	at Backuper-2.0.2-folia.jar/ru.dvdishka.shade.commandapi.CommandAPI.onEnable(CommandAPI.java:135) ~[Backuper-2.0.2-folia.jar:?]
	at Backuper-2.0.2-folia.jar/ru.dvdishka.backuper.Backuper.onEnable(Backuper.java:20) ~[Backuper-2.0.2-folia.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:610) ~[?:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:559) ~[?:?]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:720) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:464) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1221) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:350) ~[folia-1.20.6.jar:1.20.6-DEV-78f49e0]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by DVDishka** [comment]
Hm, maybe they fixed something in some build, so try to use Backuper-2.0.2.jar

**Comment by DVDishka** [comment]
Thanks for your report. Now you have to use Backuper-2.0.2 (not Folia edition) for Folia 1.20.6+

**Comment by DVDishka** [comment]
Is it ok now?

**Comment by GrimPlayzs** [comment]
Yes, the non-Folia version of the plugin works, thanks.

**Comment by melonpan0** [comment]
Same Problem has occured.

**Ubuntu 24.04, Folia ver/1.20.4@ec6b172**

[05:40:49 ERROR]: Error occurred while enabling Backuper v3.1.0 (Is it up to date?)
java.lang.IllegalStateException: Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
        at ru.dvdishka.shade.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:172) ~[Backuper-3.1.0.jar:?]
        at ru.dvdishka.shade.commandapi.CommandAPI.onEnable(CommandAPI.java:152) ~[Backuper-3.1.0.jar:?]
        at ru.dvdishka.backuper.Backuper.onEnable(Backuper.java:42) ~[Backuper-3.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:645) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:556) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by DVDishka** [comment]
Try updating your folia server jar. It was fixed in new Folia builds

**Comment by melonpan0** [comment]
Updated Folia's new version(dev/1.21.1)  and working correctly!!
Thank you for your surpport!!
